language: node_js
node_js:
  - "5.0.0"
branches:
  only:
    - master
before_script:
  - npm install --global jspm typescript typings
  - jspm install
  - typings install
  - cd tools/gulpfile.ts && typings install && cd ../../
  - npm run build

notifications:
      webhooks:
        # trigger Buildtime Trend Service to parse Travis CI log
        - https://buildtimetrend.herokuapp.com/travis
