language: node_js
node_js:
  - "5.0.0"
branches:
  only:
    - master
    
before_install:
- npm install -g npm@3.5.3
- echo "next"

before_script:
  - npm install --global jspm typescript typings
  - npm install
  - jspm install
  - typings install
  - cd tools/gulpfile.ts && typings install && cd ../../
  - ls
  - npm run build

notifications:
      webhooks:
        # trigger Buildtime Trend Service to parse Travis CI log
        - https://buildtimetrend.herokuapp.com/travis
